In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('Retail_Sales.xlsx')

In [4]:
df.head()

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0

In [5]:
df.shape

(2000, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transactions_id  2000 non-null   int64
 1   sale_date        2000 non-null   datetime64[ns]
 2   sale_time        2000 non-null   object
 3   customer_id      2000 non-null   int64
 4   gender           2000 non-null   object
 5   age              1990 non-null   float64
 6   category         2000 non-null   object
 7   quantiy          1997 non-null   float64
 8   price_per_unit   1997 non-null   float64
 9   cogs             1997 non-null   float64
 10  total_sale       1997 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(3)
memory usage: 172.0+ KB

In [7]:
df.describe()

,transactions_id,sale_date,customer_id,age,quantiy,price_per_unit,cogs,total_sale
count,2000.000000,2000,2000.000000,1990.000000,1997.000000,1997.000000,1997.000000,1997.000000
mean,1000.500000,2023-02-16 22:10:33.600000,66.341500,41.343216,2.512769,180.117677,95.023886,456.544817
min,1.000000,2022-01-01 00:00:00,1.000000,18.000000,1.000000,25.000000,6.250000,25.000000
25%,500.750000,2022-09-23 00:00:00,24.000000,29.000000,1.000000,30.000000,13.000000,60.000000
50%,1000.500000,2023-01-12 12:00:00,69.000000,42.000000,3.000000,50.000000,27.500000,150.000000
75%,1500.250000,2023-09-14 00:00:00,102.000000,53.000000,4.000000,300.000000,147.000000,900.000000
max,2000.000000,2023-12-31 00:00:00,155.000000,64.000000,4.000000,500.000000,620.000000,2000.000000
std,577.494589,NaN,44.937185,13.668167,1.132708,189.685225,121.898695,560.101381

In [8]:
df.columns

Index(['transactions_id', 'sale_date', 'sale_time', 'customer_id', 'gender',
       'age', 'category', 'quantiy', 'price_per_unit', 'cogs', 'total_sale'],
      dtype='object')

Data Cleaning

In [49]:
# Rename the column:

df.rename(columns={'quantiy': 'quantity'}, inplace=True)

In [10]:
df.isnull().sum()

transactions_id     0
sale_date           0
sale_time           0
customer_id         0
gender              0
age                10
category            0
quantity            3
price_per_unit      3
cogs                3
total_sale          3
dtype: int64

In [13]:
df['age'].mean()

np.float64(41.34321608040201)

In [14]:
df['age'].median()

42.0

In [36]:
df['age'] = df['age'].fillna(df['age'].mean())

In [16]:
df['quantity'].mean()

np.float64(2.512769153730596)

In [17]:
df['quantity'].median()

3.0

In [18]:
df['quantity'] = df['quantity'].fillna(df['quantity'].median())

In [19]:
df['price_per_unit'].mean()

np.float64(180.11767651477217)

In [20]:
df['price_per_unit'].median()

50.0

In [21]:
df['price_per_unit'] = df['price_per_unit'].fillna(df['price_per_unit'].median())

In [22]:
df['cogs'].mean()

np.float64(95.02388582874312)

In [23]:
df['cogs'].median()

27.5

In [24]:
df['cogs'] = df['cogs'].fillna(df['cogs'].median())

In [25]:
df['total_sale'].mean()

np.float64(456.54481722583876)

In [26]:
df['total_sale'].median()

150.0

In [27]:
df['total_sale'] = df['total_sale'].fillna(df['total_sale'].mean())

In [43]:
# Check the null values
df.isnull().sum()

transactions_id    0
sale_date          0
sale_time          0
customer_id        0
gender             0
age                0
category           0
quantity           0
price_per_unit     0
cogs               0
total_sale         0
sale_month         0
dtype: int64

In [44]:
# Add a new column for sale_month

df['sale_month'] = pd.to_datetime(df['sale_date']).dt.month_name()

In [30]:
df['sale_month'].head()

0    November
1        July
2    December
3     January
4    November
Name: sale_month, dtype: object

In [45]:
# Check the datatype:
df.dtypes

transactions_id             int64
sale_date          datetime64[ns]
sale_time                  object
customer_id                 int64
gender                     object
age                         int64
category                   object
quantity                    int64
price_per_unit            float64
cogs                      float64
total_sale                float64
sale_month                 object
dtype: object

In [46]:
# Change the datatype of quantity:

df['quantity'] = df['quantity'].astype(int)

In [47]:
# Change the datatype of age:

df['age'] = df['age'].astype(int)

In [50]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\asus\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\asus\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\asus\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [51]:
from sqlalchemy import create_engine

# Step 1: Connect to postgresSQL
# Replace placeholders with your actual details
username = "postgres"
password = "abhishek"
host = "localhost"
port = "5432"
database = "retail_sales"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load data
table_name = "retail"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data Successfully loaded into table '{table_name}' in database '{database}'.")

Data Successfully loaded into table 'retail' in database 'retail_sales'.